### ISSUE TITLE
docs CI is failing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/docs#2799]
e.g. #2798 - test PR to trigger CI
https://drone.owncloud.com/owncloud/docs/8315/1/4
```
11: Pulling from owncloudci/nodejs
Digest: sha256:143ab0f33d8588591a828db6ea011054572239f26db25c3ec3d33d88041369ad
Status: Image is up to date for owncloudci/nodejs:11
+ yarn validate --pull
yarn run v1.22.4
$ antora --stacktrace generate --cache-dir cache --redirect-facility disabled --generator ./generator/xref-validator.js --clean site.yml --pull
Error: Duplicate nav: 2.7@desktop:ROOT:nav.adoc
    at ContentCatalog.addFile (/drone/src/node_modules/@antora/content-classifier/lib/content-catalog.js:113:13)
    at files.forEach (/drone/src/node_modules/@antora/content-classifier/lib/classify-content.js:26:78)
    at Array.forEach (<anonymous>)
    at aggregate.reduce (/drone/src/node_modules/@antora/content-classifier/lib/classify-content.js:26:11)
    at Array.reduce (<anonymous>)
    at classifyContent (/drone/src/node_modules/@antora/content-classifier/lib/classify-content.js:22:36)
    at aggregateContent.then (/drone/src/generator/xref-validator.js:26:79)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by phil-davis** [comment]
Should be fixed by https://github.com/owncloud/client/pull/8105

This same fix was done back in 2019 - https://github.com/owncloud/client/pull/8105
